repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.9.1 # Use the latest stable version
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.50.0 # Use the latest stable version
    hooks:
      - id: eslint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0 # Use the latest stable version
    hooks:
      - id: prettier

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0 # Use the latest stable version
    hooks:
      - id: markdownlint

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.17.0 # Use the latest stable version
    hooks:
      - id: gitleaks

exclude: |
  ^static/.*
  ^node_modules/.*
